print("Hello, Project Apex!")
print("My name is Sirojiddin.")
print("I will become a Motosport Engineer.")
print("=================================")
print("Project Apex")
print("=================================")
print("Name: Sirojiddin")
print("Age: 20")
print("Major: Mathematics")
print("Goal: To become a Motosport Engineer")
print("Country: Uzbekistan")
print("===================================")
print("Every great engineer starts with one line of code and small steps.")